name: canada-service-prices
channels:
  - conda-forge
  - defaults
dependencies:
  # Core
  - python=3.12.7
  - pandas=2.2.2
  - numpy=1.26.4
  
  # Visualization
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - missingno=0.4.2
  
  # Jupyter
  - jupyterlab=4.2.5
  - ipykernel=6.28.0
