name: aespi-env
channels:
  - conda-forge
dependencies:
  # Core Analysis
  - python=3.9
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - jupyterlab
  
  # Dashboard
  - dash
  - dash-core-components
  - dash-html-components
  - geopandas
  - plotly
